name: Tests

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Tests
    runs-on: [ self-hosted ]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mysql_testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
        with:
          php-version: '8.1'
          extensions: pdo_mysql
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: List tests
        run: vendor/bin/phpunit --list-tests
      - name: Run tests
        run: vendor/bin/phpunit --testdox
